- devsnest/db/migrate/20210604064000_add_user_type_to_users.rb
- devsnest/db/migrate/20210605145138_add_google_id_to_users.rb
- devsnest/db/schema.rb
Bug fixed
Backend: `Migration Error`
- Google_id was not present in the migration
> 🐛 Migration bug solved

- devsnest/config/routes.rb
Group-member bug solved
Backend: groups-members-bug-solved
> 🐛 Group-member-bug-fixed

- .codeclimate.yml
- devsnest/Gemfile
- devsnest/Gemfile.lock
- devsnest/app/models/group.rb
- devsnest/app/models/group_member.rb
- devsnest/db/migrate/20210620062808_install_audited.rb
- devsnest/db/schema.rb
- devsnest/db/seeds.rb
+ Changes:
- Added `audited` gem.
- Setup `audited` table.
- Enabled `audited` for `Groups` and `GroupMembers` table.
- Codeclimate configure.
[Notion Task Link](https://www.notion.so/Backend-eng-101-1408fab49eb0425293c17cceced495b5)
> Audit logs

- devsnest/app/controllers/api/v1/users_controller.rb
- devsnest/app/controllers/application_controller.rb
- devsnest/app/models/user.rb
- devsnest/app/resources/api/v1/user_resource.rb
- devsnest/config/routes.rb
- devsnest/db/migrate/20210614190224_add_update_count_to_users.rb
- devsnest/db/migrate/20210619091146_add_login_count_to_users.rb
- devsnest/db/schema.rb
- devsnest/db/seeds.rb
- devsnest/spec/controllers/api/v1/users_controller_spec.rb
- devsnest/spec/factories.rb
Update Count & call by Username feature
[Notion Task Link](https://www.notion.so/User-profile-Cleanup-7dc6fc7a16d744ffb00701022453dfd2)
> ✨ [WIP]Feature

- devsnest/app/controllers/api/v1/scrums_controller.rb
- devsnest/app/models/group.rb
- devsnest/app/models/scrum.rb
- devsnest/app/resources/api/v1/scrum_resource.rb
- devsnest/config/application.rb
- devsnest/config/routes.rb
- devsnest/db/migrate/20210624163547_createscrums.rb
- devsnest/db/schema.rb
- devsnest/db/seeds.rb
Added Scrums
[Notion Task Link] https://www.notion.so/Scrums-ea9a43e7bc0548b9bc6dff7032da0081
Branches for testing
Frontend: N/A
Backend: 'yug/scrums'
Bot: N/A
> ✨Added Scrums

- devsnest/app/controllers/api/v1/scrums_controller.rb
- devsnest/app/controllers/api/v1/submissions_controller.rb
- devsnest/app/controllers/api/v1/weekly_todo_controller.rb
- devsnest/app/models/group.rb
- devsnest/app/models/weekly_todo.rb
- devsnest/app/resources/api/v1/content_resource.rb
- devsnest/app/resources/api/v1/group_member_resource.rb
- devsnest/app/resources/api/v1/group_resource.rb
- devsnest/app/resources/api/v1/weekly_todo_resource.rb
- devsnest/config/routes.rb
- devsnest/db/migrate/20210629162155_create_weekly_todo.rb
- devsnest/db/schema.rb
- devsnest/db/seeds.rb
- devsnest/spec/controllers/api/v1/users_controller_spec.rb
- devsnest/spec/controllers/api/v1/weekly_todo_controller_spec.rb
- devsnest/spec/factories.rb
- devsnest/spec/rails_helper.rb
- devsnest/spec/requests/weekly_todo_spec.rb
[Notion Task Link](https://www.notion.so/Groups-Weekly-Todo-6e9dfe9d1a924ce3a6a236cb9fa3b272)
Backend: group_weekly_todo
> Group weekly todo

- .codeclimate.yml
- devsnest/app/controllers/api/v1/frontend_submissions_controller.rb
- devsnest/app/models/frontend_submission.rb
- devsnest/app/resources/api/v1/content_resource.rb
- devsnest/app/resources/api/v1/frontend_submission_resource.rb
- devsnest/config/database.yml
- devsnest/config/routes.rb
- devsnest/db/migrate/20210701035706_create_frontend_submissions.rb
- devsnest/db/schema.rb
- devsnest/db/seeds.rb
- devsnest/lib/tasks/frontend.rake
- devsnest/scripts/FrontendContent.csv
- devsnest/spec/controllers/api/v1/frontend_submissions_controller_spec.rb
- devsnest/spec/factories.rb
- devsnest/spec/requests/frontend_submissions_controller_spec.rb
Submissions-Onepage-ui for frontend
[Notion Task Link](https://www.notion.so/3d6d8bec59b7483bbaeb98bac21458ec?v=73a0d569661641dbb7e4c318e2b6118f&p=5a66c2ce725943a69cbfc3d7763555ae)
> Submission onepage

- devsnest/app/controllers/api/v1/scrums_controller.rb
- devsnest/app/models/group.rb
- devsnest/app/resources/api/v1/scrum_resource.rb
- devsnest/config/database.yml
- devsnest/spec/factories.rb
- devsnest/spec/models/scrum_spec.rb
- devsnest/spec/requests/scrum_request_spec.rb
> ✨ Added Scrum_History and Model Specs for that

- devsnest/spec/factories.rb
- devsnest/spec/models/content_spec.rb
- devsnest/spec/requests/submissions_spec.rb
Notion link : https://www.notion.so/3d6d8bec59b7483bbaeb98bac21458ec?v=73a0d569661641dbb7e4c318e2b6118f&p=175f80819f2743709b3fb28f3dbd74bd
> 📈 submission Rspec

- devsnest/spec/factories.rb
- devsnest/spec/models/content_spec.rb
- devsnest/spec/requests/submissions_spec.rb
> 📈 submission Rspec (#108)

- devsnest/app/resources/api/v1/batch_leader_sheet_resource.rb
- devsnest/app/resources/api/v1/scrum_resource.rb
- devsnest/db/migrate/20210727064241_add_bl_fields.rb
- devsnest/db/migrate/20210727092546_add_last_tha_link_to_scrums.rb
- devsnest/db/schema.rb
> Revert "Bl fields"

- devsnest/app/controllers/api/v1/users_controller.rb
- devsnest/db/seeds.rb
Current user will be on top of leaderboard
> Leaderboard_fix

- devsnest/app/controllers/api/v1/markdown_controller.rb
- devsnest/app/controllers/api/v1/users_controller.rb
- devsnest/app/models/markdown.rb
- devsnest/app/resources/api/v1/markdown_resource.rb
- devsnest/app/resources/api/v1/user_resource.rb
- devsnest/config/routes.rb
- devsnest/db/migrate/20210705181526_add_discord_username_to_user.rb
- devsnest/db/migrate/20210721175353_create_markdowns.rb
- devsnest/db/schema.rb
- devsnest/db/seeds.rb
- devsnest/spec/models/user_spec.rb
- devsnest/spec/requests/api/v1/user_request_spec.rb
- devsnest/spec/support/factories_support.rb
> Adhikram public profile

- devsnest/app/controllers/api/v1/groups_controller.rb
- devsnest/app/controllers/api/v1/scrums_controller.rb
- devsnest/app/controllers/api/v1/users_controller.rb
- devsnest/config/routes.rb
- devsnest/db/schema.rb
- devsnest/spec/requests/api/v1/user_request_spec.rb
> 🔥Bot syncs

- devsnest/app/resources/api/v1/group_member_resource.rb
> 🔥 Added name in groupmembers details

- devsnest/app/controllers/api/v1/admin_controller.rb
- devsnest/app/controllers/api/v1/internal_feedback_controller.rb
- devsnest/app/models/internal_feedback.rb
- devsnest/app/models/user.rb
- devsnest/app/resources/api/v1/internal_feedback_resource.rb
- devsnest/config/database.yml
- devsnest/config/routes.rb
- devsnest/db/migrate/20210718051018_create_internal_feedbacks.rb
- devsnest/db/schema.rb
- devsnest/spec/factories.rb
- devsnest/spec/models/internal_feedback_spec.rb
- devsnest/spec/requests/api/v1/admin_request_spec.rb
- devsnest/spec/requests/api/v1/internal_feedback_spec.rb
[Notion Task Link](https://www.notion.so/Internal-Feedback-System-4bb77950c36a4e43a90ce026f0dab7cd)
> Internal feedback

- devsnest/app/controllers/api/v1/weekly_todo_controller.rb
- devsnest/app/resources/api/v1/weekly_todo_resource.rb
- devsnest/config/database.yml
- devsnest/spec/requests/weekly_todo_spec.rb
> Weekly todo fixed

- devsnest/app/controllers/api/v1/internal_feedback_controller.rb
- devsnest/app/models/internal_feedback.rb
- devsnest/app/resources/api/v1/internal_feedback_resource.rb
- devsnest/db/migrate/20210807185424_add_user_name_to_internal_feedback.rb
- devsnest/db/schema.rb
> added username | internal feedback (#131)

- devsnest/app/models/group.rb
- devsnest/app/resources/api/v1/scrum_resource.rb
- devsnest/spec/requests/scrum_request_spec.rb
Scrum History Can be viewed by Any member of group and batch leader and admin
> Scrum Permission Fixed

- devsnest/app/models/group.rb
- devsnest/app/resources/api/v1/scrum_resource.rb
- devsnest/spec/requests/scrum_request_spec.rb
Now Whole Team can view Scrum history
> Scrum History Permission Fixed

- devsnest/db/seeds.rb
> 🌱 added seedfile

- devsnest/app/controllers/api/v1/link_controller.rb
- devsnest/app/models/link.rb
- devsnest/app/resources/api/v1/link_resource.rb
- devsnest/config/routes.rb
- devsnest/db/migrate/20210816053445_create_links.rb
- devsnest/db/schema.rb
- devsnest/spec/factories.rb
- devsnest/spec/requests/link_spec.rb
[Notion Task Link](https://www.notion.so/URL-Shortener-930a40d5ed154f2e88afe15f2c673c8d)
> [WIP] Url shortner

- devsnest/app/controllers/api/v1/link_controller.rb
- devsnest/app/models/link.rb
- devsnest/app/resources/api/v1/link_resource.rb
- devsnest/config/routes.rb
- devsnest/db/migrate/20210816053445_create_links.rb
- devsnest/db/schema.rb
- devsnest/spec/factories.rb
- devsnest/spec/requests/link_spec.rb
> 🎨 🔥 Updated feature

- devsnest/app/models/user.rb
Merging user error:-
if previous_user is owner or co_owner of a group
Score update of new user
> 🐛Merging user  Bug Fixed

- devsnest/app/controllers/api/v1/users_controller.rb
- devsnest/db/seeds.rb
- devsnest/spec/requests/content_spec.rb
* content spec
* leaderboard fix
* 🌱 seed file fix
> content spec (#165)

- devsnest/app/resources/api/v1/hackathon_resource.rb
- devsnest/db/migrate/20210901061201_add_participants_to_hackathon.rb
> 🐛 added participants to hackathon

- devsnest/spec/requests/user_spec.rb
> 🔥 Login and connect discord

- devsnest/app/controllers/api/v1/admin/challenge_controller.rb
- devsnest/app/controllers/application_controller.rb
- devsnest/app/models/challenge.rb
- devsnest/app/models/user.rb
- devsnest/app/resources/api/v1/admin/challenge_resource.rb
- devsnest/config/routes.rb
- devsnest/db/migrate/20211117145543_add_tester_code_to_challenges.rb
- devsnest/db/schema.rb
- devsnest/spec/requests/admin/challenge_spec.rb
* Added APIS for admin panel algo editor
> algo editor admin panel (#230)

- devsnest/app/models/frontend_question.rb
- devsnest/app/models/minibootcamp.rb
- devsnest/db/migrate/20211208140925_create_minibootcamp.rb
- devsnest/db/migrate/20211213184521_create_frontend_questions.rb
- devsnest/db/schema.rb
> Submissions-from-s3

- devsnest/Gemfile.lock
> ⬆️ Upgrade FFI

- devsnest/app/controllers/api/v1/challenge_controller.rb
- devsnest/app/controllers/concerns/api_render_concern.rb
- devsnest/app/models/challenge.rb
- devsnest/app/resources/api/v1/algo_submission_resource.rb
- devsnest/lib/algo_templates/base_helper.rb
- devsnest/lib/algo_templates/cpp.rb
- devsnest/lib/algo_templates/java.rb
- devsnest/lib/algo_templates/javascript.rb
- devsnest/lib/algo_templates/python2.rb
- devsnest/lib/algo_templates/python3.rb
- devsnest/spec/models/challenge_spec.rb
> Algo rspec

- devsnest/app/models/algo_submission.rb
change max thread limit from 10 to 120
> change jugde zero configs

- devsnest/app/controllers/api/v1/groups_controller.rb
- devsnest/app/controllers/api/v1/users_controller.rb
> 🐛 🚑 Final edits

- devsnest/db/migrate/20220525063722_add_column_type_linked_list_to_languages.rb
- devsnest/db/schema.rb
> Ll template db setup

- devsnest/app/controllers/api/v1/groups_controller.rb
- devsnest/app/models/group.rb
- devsnest/app/resources/api/v1/group_resource.rb
- devsnest/app/workers/mass_role_modifier_worker.rb
- devsnest/db/schema.rb
- devsnest/scripts/allScripts.rb
> 🔥 group limit update

- devsnest/app/controllers/api/v1/groups_controller.rb
> Revert "🐛 update fix"

- devsnest/app/controllers/api/v1/groups_controller.rb
> 🚑 update feature

- devsnest/app/models/challenge.rb
> hotfix templates api

- devsnest/app/controllers/api/v1/admin/groups_controller.rb
- devsnest/app/controllers/api/v1/group_members_controller.rb
- devsnest/app/models/group.rb
- devsnest/app/resources/api/v1/admin/group_resource.rb
- devsnest/app/workers/mass_role_modifier_worker.rb
- devsnest/config/routes.rb
- devsnest/db/schema.rb
> Group merging yug

- devsnest/app/resources/api/v1/algo_submission_resource.rb
- devsnest/lib/algo_templates/base_helper.rb
> java str fix

- devsnest/lib/algo_templates/base_helper.rb
> java arg fix

- devsnest/lib/algo_templates/base_helper.rb
> check only for prim

- devsnest/app/models/challenge.rb
- devsnest/lib/algo_templates/cpp.rb
- devsnest/lib/algo_templates/java.rb
- devsnest/lib/algo_templates/python3.rb
> day 2 java n cpp fixes

- devsnest/app/controllers/api/v1/group_members_controller.rb
- devsnest/app/models/group.rb
- devsnest/db/migrate/20220620114859_add_index_to_member_count.rb
- devsnest/db/schema.rb
> Group remove and merge, role remove from discord

- devsnest/app/resources/api/v1/user_resource.rb
> Removing critical fields from user show

- devsnest/db/migrate/20220624120018_algo_submission_opt.rb
- devsnest/db/schema.rb
> Remove/Modifying Algo Submissions index

- devsnest/app/controllers/api/v1/algo_submission_controller.rb
> sleep to 1

- devsnest/app/controllers/api/v1/algo_submission_controller.rb
- devsnest/app/models/algo_submission.rb
- devsnest/config/environments/development.rb
- devsnest/db/schema.rb
- devsnest/lib/tasks/ch_bs.rake
- devsnest/lib/tasks/recreate_pending_subs.rake
> Algo fixes

- devsnest/app/models/group_member.rb
- devsnest/app/resources/api/v1/group_resource.rb
> removing group caching

- devsnest/app/models/algo_submission.rb
> find or create

- devsnest/app/models/algo_submission.rb
> simpfying UCS creation

- devsnest/app/controllers/api/v1/users_controller.rb
- devsnest/app/models/group.rb
- devsnest/app/models/scrum.rb
- devsnest/app/models/user.rb
- devsnest/config/routes.rb
- devsnest/spec/factories.rb
- devsnest/spec/requests/user_spec.rb
API:- /api/v1/users/dashboard_details
Data:-
> Initial Commit

- devsnest/app/controllers/api/v1/groups_controller.rb
- devsnest/app/controllers/api/v1/users_controller.rb
> users can join groups

- devsnest/app/controllers/api/v1/algo_submission_controller.rb
- devsnest/app/controllers/api/v1/coding_rooms_controller.rb
- devsnest/app/models/algo_submission.rb
- devsnest/app/models/certification.rb
- devsnest/app/models/challenge.rb
- devsnest/app/models/coding_room.rb
- devsnest/app/models/coding_room_user_mapping.rb
- devsnest/app/models/room_best_submission.rb
- devsnest/app/models/user.rb
- devsnest/app/resources/api/v1/algo_submission_resource.rb
- devsnest/app/resources/api/v1/coding_room_resource.rb
- devsnest/app/workers/close_room_worker.rb
- devsnest/config/initializers/leaderboard.rb
- devsnest/config/routes.rb
- devsnest/db/migrate/20221215095628_add_coding_room_and_mappings.rb
- devsnest/db/migrate/20221222093330_add_coding_room_id_to_algo_submission.rb
- devsnest/db/migrate/20221230091521_create_room_best_submission.rb
- devsnest/db/schema.rb
- devsnest/db/seeds/coding_room_seed.rb
- devsnest/spec/models/algo_submission_spec.rb
> Coding Rooms

- devsnest/app/controllers/api/v1/users_controller.rb
- devsnest/app/models/backend_challenge_score.rb
- devsnest/app/models/certification.rb
- devsnest/app/models/user.rb
- devsnest/spec/models/user_spec.rb
> Google auth changes

- devsnest/app/controllers/api/v1/admin/groups_controller.rb
- devsnest/app/resources/api/v1/group_resource.rb
- devsnest/config/routes.rb
> Admin group creation
